# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, DialogWindow):
        DialogWindow.setObjectName("DialogWindow")
        DialogWindow.setGeometry(QtCore.QRect(0, 0, 471, 472))
        self.centralwidget = QtWidgets.QWidget(parent=DialogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(130, 50, 211, 21))
        self.nameEdit.setObjectName("nameEdit")
        self.roastEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastEdit.setGeometry(QtCore.QRect(130, 90, 211, 21))
        self.roastEdit.setObjectName("roastEdit")
        self.typeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.typeEdit.setGeometry(QtCore.QRect(130, 130, 211, 21))
        self.typeEdit.setObjectName("typeEdit")
        self.descEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.descEdit.setGeometry(QtCore.QRect(130, 170, 211, 21))
        self.descEdit.setObjectName("descEdit")
        self.priceEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceEdit.setGeometry(QtCore.QRect(130, 210, 211, 21))
        self.priceEdit.setText("")
        self.priceEdit.setObjectName("priceEdit")
        self.volumeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.volumeEdit.setGeometry(QtCore.QRect(130, 250, 211, 21))
        self.volumeEdit.setText("")
        self.volumeEdit.setObjectName("volumeEdit")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(190, 310, 75, 24))
        self.saveButton.setObjectName("saveButton")
        self.menubar = QtWidgets.QMenuBar(parent=DialogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 22))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(parent=DialogWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(DialogWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogWindow)

    def retranslateUi(self, DialogWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameEdit.setPlaceholderText(_translate("MainWindow", "название"))
        self.roastEdit.setPlaceholderText(_translate("MainWindow", "степень обжарки"))
        self.typeEdit.setPlaceholderText(_translate("MainWindow", "тип кофе (молотый/в зернах)"))
        self.descEdit.setPlaceholderText(_translate("MainWindow", "описание"))
        self.priceEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>цена</p></body></html>"))
        self.priceEdit.setPlaceholderText(_translate("MainWindow", "цена"))
        self.volumeEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>цена</p></body></html>"))
        self.volumeEdit.setPlaceholderText(_translate("MainWindow", "количество"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
