# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 470)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.coffeeTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coffeeTable.setGeometry(QtCore.QRect(50, 20, 701, 341))
        self.coffeeTable.setObjectName("coffeeTable")
        self.coffeeTable.setColumnCount(0)
        self.coffeeTable.setRowCount(0)
        self.refreshButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(50, 380, 91, 31))
        self.refreshButton.setObjectName("refreshButton")
        self.addEditButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addEditButton.setGeometry(QtCore.QRect(170, 380, 151, 31))
        self.addEditButton.setObjectName("addEditButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refreshButton.setText(_translate("MainWindow", "Обновить"))
        self.addEditButton.setText(_translate("MainWindow", "Добавить/редактировать"))
